# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1164, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.carrierEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.carrierEdit.setObjectName("carrierEdit")
        self.gridLayout.addWidget(self.carrierEdit, 0, 1, 1, 2)
        self.carrierButton = QtWidgets.QPushButton(self.centralwidget)
        self.carrierButton.setObjectName("carrierButton")
        self.gridLayout.addWidget(self.carrierButton, 0, 3, 1, 2)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.secretEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.secretEdit.setObjectName("secretEdit")
        self.gridLayout.addWidget(self.secretEdit, 1, 1, 1, 2)
        self.secretButton = QtWidgets.QPushButton(self.centralwidget)
        self.secretButton.setObjectName("secretButton")
        self.gridLayout.addWidget(self.secretButton, 1, 3, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 2, 4, 1, 1)
        self.carrierImage = QtWidgets.QLabel(self.centralwidget)
        self.carrierImage.setText("")
        self.carrierImage.setObjectName("carrierImage")
        self.gridLayout.addWidget(self.carrierImage, 3, 0, 1, 2)
        self.graphicsView_3 = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.gridLayout.addWidget(self.graphicsView_3, 3, 4, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 2)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setObjectName("textBrowser")
        self.gridLayout.addWidget(self.textBrowser, 5, 0, 1, 3)
        self.encodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.encodeButton.setObjectName("encodeButton")
        self.gridLayout.addWidget(self.encodeButton, 5, 4, 1, 1)
        self.decodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.decodeButton.setObjectName("decodeButton")
        self.gridLayout.addWidget(self.decodeButton, 5, 5, 1, 1)
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 5, 6, 1, 1)
        self.secretImage = QtWidgets.QLabel(self.centralwidget)
        self.secretImage.setText("")
        self.secretImage.setObjectName("secretImage")
        self.gridLayout.addWidget(self.secretImage, 3, 2, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1164, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Carrier File:"))
        self.carrierButton.setText(_translate("MainWindow", "Select Carrier"))
        self.label_2.setText(_translate("MainWindow", "Secret File:"))
        self.secretButton.setText(_translate("MainWindow", "Select Secret"))
        self.label_4.setText(_translate("MainWindow", "Carrier File"))
        self.label_5.setText(_translate("MainWindow", "Secret File"))
        self.label_6.setText(_translate("MainWindow", "Output File"))
        self.label_3.setText(_translate("MainWindow", "Console Output:"))
        self.encodeButton.setText(_translate("MainWindow", "Encode Image"))
        self.decodeButton.setText(_translate("MainWindow", "Decode"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))

