# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1164, 705)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.secretEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.secretEdit.setObjectName("secretEdit")
        self.gridLayout.addWidget(self.secretEdit, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.carrierImage = QtWidgets.QLabel(self.centralwidget)
        self.carrierImage.setText("")
        self.carrierImage.setObjectName("carrierImage")
        self.verticalLayout.addWidget(self.carrierImage)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_6.setObjectName("label_6")
        self.verticalLayout_2.addWidget(self.label_6)
        self.encodedImage = QtWidgets.QLabel(self.centralwidget)
        self.encodedImage.setText("")
        self.encodedImage.setObjectName("encodedImage")
        self.verticalLayout_2.addWidget(self.encodedImage)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 6)
        self.encodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.encodeButton.setObjectName("encodeButton")
        self.gridLayout.addWidget(self.encodeButton, 5, 3, 1, 1)
        self.secretButton = QtWidgets.QPushButton(self.centralwidget)
        self.secretButton.setObjectName("secretButton")
        self.gridLayout.addWidget(self.secretButton, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.carrierEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.carrierEdit.setObjectName("carrierEdit")
        self.gridLayout.addWidget(self.carrierEdit, 0, 1, 1, 1)
        self.exitButton = QtWidgets.QPushButton(self.centralwidget)
        self.exitButton.setObjectName("exitButton")
        self.gridLayout.addWidget(self.exitButton, 5, 5, 1, 1)
        self.encodedEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.encodedEdit.setObjectName("encodedEdit")
        self.gridLayout.addWidget(self.encodedEdit, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.carrierButton = QtWidgets.QPushButton(self.centralwidget)
        self.carrierButton.setObjectName("carrierButton")
        self.gridLayout.addWidget(self.carrierButton, 0, 2, 1, 1)
        self.decodeButton = QtWidgets.QPushButton(self.centralwidget)
        self.decodeButton.setObjectName("decodeButton")
        self.gridLayout.addWidget(self.decodeButton, 5, 4, 1, 1)
        self.encodeFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.encodeFileButton.setObjectName("encodeFileButton")
        self.gridLayout.addWidget(self.encodeFileButton, 2, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1164, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_2.setText(_translate("MainWindow", "Secret File:"))
        self.label_8.setText(_translate("MainWindow", "Carrier File"))
        self.label_6.setText(_translate("MainWindow", "Output File"))
        self.encodeButton.setText(_translate("MainWindow", "Encode Image"))
        self.secretButton.setText(_translate("MainWindow", "Select Secret"))
        self.label_7.setText(_translate("MainWindow", "Encoded File"))
        self.exitButton.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "Carrier File:"))
        self.carrierButton.setText(_translate("MainWindow", "Select Carrier"))
        self.decodeButton.setText(_translate("MainWindow", "Decode"))
        self.encodeFileButton.setText(_translate("MainWindow", "Select Encoded"))

