# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(600, 400)
        MainWindow.setMinimumSize(QtCore.QSize(400, 200))
        MainWindow.setMaximumSize(QtCore.QSize(600, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setMinimumSize(QtCore.QSize(90, 0))
        self.label.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        self.input_sendReceiverIp = QtWidgets.QLineEdit(self.tab)
        self.input_sendReceiverIp.setObjectName("input_sendReceiverIp")
        self.horizontalLayout_5.addWidget(self.input_sendReceiverIp)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.tab)
        self.label_2.setMinimumSize(QtCore.QSize(90, 0))
        self.label_2.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.input_sendBouncerIp = QtWidgets.QLineEdit(self.tab)
        self.input_sendBouncerIp.setObjectName("input_sendBouncerIp")
        self.horizontalLayout_9.addWidget(self.input_sendBouncerIp)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_5 = QtWidgets.QLabel(self.tab)
        self.label_5.setMinimumSize(QtCore.QSize(90, 0))
        self.label_5.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        self.input_sendPort = QtWidgets.QSpinBox(self.tab)
        self.input_sendPort.setMaximum(65535)
        self.input_sendPort.setProperty("value", 139)
        self.input_sendPort.setObjectName("input_sendPort")
        self.horizontalLayout_10.addWidget(self.input_sendPort)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.tab)
        self.label_6.setMinimumSize(QtCore.QSize(90, 0))
        self.label_6.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_8.addWidget(self.label_6)
        self.input_sendMessage = QtWidgets.QLineEdit(self.tab)
        self.input_sendMessage.setObjectName("input_sendMessage")
        self.horizontalLayout_8.addWidget(self.input_sendMessage)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_7 = QtWidgets.QLabel(self.tab)
        self.label_7.setMinimumSize(QtCore.QSize(90, 0))
        self.label_7.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_12.addWidget(self.label_7)
        self.input_sendMinWait = QtWidgets.QSpinBox(self.tab)
        self.input_sendMinWait.setMaximum(100000)
        self.input_sendMinWait.setProperty("value", 100)
        self.input_sendMinWait.setObjectName("input_sendMinWait")
        self.horizontalLayout_12.addWidget(self.input_sendMinWait)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_8 = QtWidgets.QLabel(self.tab)
        self.label_8.setMinimumSize(QtCore.QSize(90, 0))
        self.label_8.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_13.addWidget(self.label_8)
        self.input_sendMaxWait = QtWidgets.QSpinBox(self.tab)
        self.input_sendMaxWait.setMaximum(100000)
        self.input_sendMaxWait.setProperty("value", 500)
        self.input_sendMaxWait.setObjectName("input_sendMaxWait")
        self.horizontalLayout_13.addWidget(self.input_sendMaxWait)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.progressBar = QtWidgets.QProgressBar(self.tab)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout_2.addWidget(self.progressBar)
        self.btn_sendMessage = QtWidgets.QPushButton(self.tab)
        self.btn_sendMessage.setObjectName("btn_sendMessage")
        self.verticalLayout_2.addWidget(self.btn_sendMessage)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.tab_2)
        self.label_3.setMinimumSize(QtCore.QSize(90, 0))
        self.label_3.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.input_recvIp = QtWidgets.QLineEdit(self.tab_2)
        self.input_recvIp.setObjectName("input_recvIp")
        self.horizontalLayout_3.addWidget(self.input_recvIp)
        self.verticalLayout_7.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.tab_2)
        self.label_4.setMinimumSize(QtCore.QSize(90, 0))
        self.label_4.setMaximumSize(QtCore.QSize(90, 16777215))
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.input_recvPort = QtWidgets.QSpinBox(self.tab_2)
        self.input_recvPort.setMaximum(65535)
        self.input_recvPort.setProperty("value", 139)
        self.input_recvPort.setObjectName("input_recvPort")
        self.horizontalLayout_4.addWidget(self.input_recvPort)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addLayout(self.verticalLayout_7)
        self.btn_startReceiver = QtWidgets.QPushButton(self.tab_2)
        self.btn_startReceiver.setObjectName("btn_startReceiver")
        self.horizontalLayout_6.addWidget(self.btn_startReceiver)
        self.verticalLayout_5.addLayout(self.horizontalLayout_6)
        self.list_allMessages = QtWidgets.QListWidget(self.tab_2)
        self.list_allMessages.setObjectName("list_allMessages")
        self.verticalLayout_5.addWidget(self.list_allMessages)
        self.btn_clearMessages = QtWidgets.QPushButton(self.tab_2)
        self.btn_clearMessages.setObjectName("btn_clearMessages")
        self.verticalLayout_5.addWidget(self.btn_clearMessages)
        self.verticalLayout_3.addLayout(self.verticalLayout_5)
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Receiver IP"))
        self.input_sendReceiverIp.setText(_translate("MainWindow", "192.168.1.69"))
        self.label_2.setText(_translate("MainWindow", "Bouncer IP"))
        self.input_sendBouncerIp.setText(_translate("MainWindow", "192.168.1.80"))
        self.label_5.setText(_translate("MainWindow", "Bouncer Port"))
        self.label_6.setText(_translate("MainWindow", "Message"))
        self.input_sendMessage.setText(_translate("MainWindow", "Hello World!"))
        self.label_7.setText(_translate("MainWindow", "Min Wait (ms)"))
        self.label_8.setText(_translate("MainWindow", "Max Wait (ms)"))
        self.btn_sendMessage.setText(_translate("MainWindow", "Send Message"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Sender"))
        self.label_3.setText(_translate("MainWindow", "Bouncer IP"))
        self.input_recvIp.setText(_translate("MainWindow", "192.168.1.80"))
        self.label_4.setText(_translate("MainWindow", "Bouncer Port"))
        self.btn_startReceiver.setText(_translate("MainWindow", "Start Receiver"))
        self.btn_clearMessages.setText(_translate("MainWindow", "Clear Messages"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Receiver"))

